=== Sergey-Teslya/Lessons_Java/target/classes/XML_JSON/XML/XMLTest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="catalog" type="catalogType">
    <xs:annotation>
      <xs:documentation><![CDATA[DTD = Document Type Definition. Это интсрукция по обработке либо валидатор<!DOCTYPE catalog [<!ELEMENT catalog (book)*><!ELEMENT book (author|title|genre|price|publish_date)*><!ELEMENT author (#PCDATA)><!ELEMENT title (#PCDATA)><!ELEMENT genre (#PCDATA)><!ELEMENT price (#PCDATA)><!ATTLIST pricecurrency CDATA #IMPLIED><!ELEMENT publish_date (#PCDATA)>]>]]></xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="bookType">
    <xs:sequence>
      <xs:element name="author">
        <xs:annotation>
          <xs:documentation>Указатели на символы:
            &amp;lt;  >
            &amp;gt;  &lt;</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="&lt;Gambardella&gt;, Matthew"/>
            <xs:enumeration value="Ralls, Kim"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <!-- Сделали нашу схему короче, и более читабельной, и при этом компактной и более гибкой -->
      <!-- Теперь в эти теги можем вносить разные значения, а не только те что внесли изначально, и это динамически гибкой -->
      <xs:element name="title" type="xs:string" />
      <xs:element name="genre" type="xs:string" />

      <xs:element name="price">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute type="xs:string" name="currency" use="optional"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>

      <xs:element name="publish_date">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="2000-10-01"/>
            <xs:enumeration value="2000-12-16"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="priceType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="currency" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="catalogType">
    <xs:sequence>
      <xs:element type="bookType" name="book" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs1:attribute ref="xs:noNamespaceSchemaLocation" xmlns:xs="https://www.w3.org/2001/XMLSchema-instance" xmlns:xs1="http://www.w3.org/2001/XMLSchema"/>
  </xs:complexType>
  <xs:attribute name="noNamespaceSchemaLocation"></xs:attribute>
</xs:schema>

=== Sergey-Teslya/Lessons_Java/target/classes/XML_JSON/XML/XMLTest.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- Есть два способа как указать описание XML_JSON файла, чтобы в последствии случайно не поменять его -->
<!-- DTD = Document Type Definition. Это интсрукция по обработке либо валидатор-->
<!-- XSD = Это тоже валидатор. Это как класс, это схема к определенному XML_JSON. XML_JSON - это уже как конкретный объект-->

<!--Вот так мы описываем DTD к нашему XML_JSON файлу -->
<!DOCTYPE catalog [
        <!ELEMENT catalog (book)*>
        <!ELEMENT book (author|title|genre|price|publish_date)*>
        <!ELEMENT author (#PCDATA)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT genre (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ATTLIST price
                currency CDATA #IMPLIED>
        <!ELEMENT publish_date (#PCDATA)>
        ]>

<!--Вот так мы подключаем XSD к нашему XML_JSON файлу -->
<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="XMLTest.xsd">
    <book>
        <!--
            Указатели на символы:
            &lt;  >
            &gt;  <
        -->
        <author>&lt;Gambardella&gt;, Matthew</author>
        <title>XML_JSON Developer's Guide</title>
        <genre>Computer</genre>
        <price>44.95</price>
        <publish_date>2000-10-01</publish_date>
    </book>
    <book>
        <author>Ralls, Kim</author>
        <title>Midnight Rain</title>
        <genre>Fantasy</genre>
        <price currency="USD">5.95</price>
        <publish_date>2000-12-16</publish_date>
    </book>


</catalog>
